spring.application.name=demo
server.address=0.0.0.0
server.port=${PORT:8080}

# Conexión manual ultra-segura para Railway
# Reconstruimos la URL de JDBC usando las variables que Railway inyecta por defecto
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:granada_flats}
spring.datasource.username=${PGUSER:sa}
spring.datasource.password=${PGPASSWORD:}
spring.datasource.driverClassName=org.postgresql.Driver

# Configuración de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactivar seguridad CSRF
spring.security.csrf.disable=true
